site_name: qrcode_song
pages:
    - Home: index.md
    - About: about.md
theme: readthedocs
markdown_extensions:
    - pymdownx.arithmatex
extra_javascript:
    - docs/js/mathjax-config.js
    - docs/js/MathJax.js